global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: linux-observability-vmware-targets
    static_configs:
      - targets:
          - 192.168.8.129:9100
          - 192.168.8.130:9100
        labels:
          lab: 01-linux-observability-lab
          role: linux-observability-target
          environment: vmware-local