name: snsd-container-runtime-lab

services:
  container-web:
    image: nginx:stable-alpine
    ports:
      - "18080:80"
    volumes:
      - ../configs/index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped