[openstack]
openstack-node ansible_host=192.168.1.10

[proxy]
proxy-network-node ansible_host=192.168.1.20

[app]
app-node-01 ansible_host=192.168.1.31
app-node-02 ansible_host=192.168.1.32

[data_ops]
data-ops-node ansible_host=192.168.1.40

[monitoring]
data-ops-node ansible_host=192.168.1.40

[logging]
data-ops-node ansible_host=192.168.1.40

[backup]
data-ops-node ansible_host=192.168.1.40

[resilience]
proxy-network-node ansible_host=192.168.1.20
app-node-01 ansible_host=192.168.1.31
app-node-02 ansible_host=192.168.1.32

[ubuntu_nodes:children]
openstack
proxy
app
data_ops

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/snsd-lab
ansible_python_interpreter=/usr/bin/python3
ansible_become=true
ansible_become_method=sudo
