[control]
localhost ansible_connection=local

[managed]
mock-web-01 ansible_host=127.0.0.1 ansible_connection=local
mock-db-01 ansible_host=127.0.0.1 ansible_connection=local

[recovery_targets]
mock-web-01
mock-db-01
